# Generated by Django 2.2.4 on 2020-09-18 02:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
                ('what', models.CharField(blank=True, max_length=100, null=True)),
                ('how_many', models.CharField(blank=True, max_length=100, null=True)),
                ('action_from', models.CharField(blank=True, max_length=100, null=True)),
                ('action_to', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webInventory.Profile')),
            ],
        ),
    ]
