# Generated by Django 2.2.4 on 2020-09-18 21:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webInventory', '0005_auto_20200919_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 21, 54, 29, 538384, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 21, 54, 29, 537387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemfolder',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 21, 54, 29, 536355, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 21, 54, 29, 537387, tzinfo=utc)),
        ),
    ]
