# Generated by Django 2.2.4 on 2020-09-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInventory', '0007_auto_20200919_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
