# Generated by Django 3.1.1 on 2020-09-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInventory', '0009_auto_20200920_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
