# Generated by Django 3.1.1 on 2020-09-29 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webInventory', '0011_tag_created_by_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audittrail',
            name='profile',
        ),
        migrations.AddField(
            model_name='audittrail',
            name='profile_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audittrail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
