# Generated by Django 3.1.1 on 2020-10-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webInventory', '0015_profile_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audittrail',
            name='user',
        ),
    ]
