# Generated by Django 3.1.1 on 2020-11-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInventory', '0017_audittrail_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
