# Generated by Django 3.1.1 on 2020-11-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInventory', '0019_companyinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
