# Generated by Django 3.1.1 on 2020-11-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webInventory', '0023_auto_20201129_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='companyPrefix',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
